export const ErrorCodeEnum = {
    // Authentication Errors
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_INVALID_SESSION: 'AUTH_INVALID_SESSION',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_NOT_FOUND: 'AUTH_NOT_FOUND',
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
    AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',
    AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR', // Added for P1010
    AUTH_SESSION_TIMED_OUT: 'AUTH_SESSION_TIMED_OUT',

    // Authorization Errors
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
    ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',

    // General HTTP Errors
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    CONFLICT: 'CONFLICT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',

    // Rate Limiting and Timeouts
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR',
    REQUEST_TIMEOUT: 'REQUEST_TIMEOUT', // Fixed duplicate key issue
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

    // User Errors
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

    // Business Logic Errors
    BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

    // Resource Generic Errors
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

    // Validation Errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DATA_TYPE_ERROR: 'DATA_TYPE_ERROR', // Added for P2005, P2006
    INPUT_ERROR: 'INPUT_ERROR', // Added for P2019
    VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE', // Added for P2020
    NUMBER_OUT_OF_RANGE: 'NUMBER_OUT_OF_RANGE', // Added for P2033
    REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING', // Added for P2012, P2013

    // Database Connection Errors
    DATABASE_ERROR: 'DATABASE_ERROR',
    DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
    DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
    CONNECTION_POOL_TIMEOUT: 'CONNECTION_POOL_TIMEOUT', // Added for P2024

    // Database Constraint Errors
    FOREIGN_KEY_CONSTRAINT: 'FOREIGN_KEY_CONSTRAINT',
    UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
    CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
    NULL_CONSTRAINT_VIOLATION: 'NULL_CONSTRAINT_VIOLATION', // Added for P2011
    RELATION_VIOLATION: 'RELATION_VIOLATION',

    // Database Query Errors
    QUERY_PARSE_ERROR: 'QUERY_PARSE_ERROR', // Added for P2008
    QUERY_VALIDATION_ERROR: 'QUERY_VALIDATION_ERROR', // Added for P2009
    QUERY_EXECUTION_ERROR: 'QUERY_EXECUTION_ERROR', // Added for P2010
    QUERY_INTERPRETATION_ERROR: 'QUERY_INTERPRETATION_ERROR', // Added for P2016

    // Database Schema Errors
    TABLE_NOT_FOUND: 'TABLE_NOT_FOUND', // Added for P2021
    COLUMN_NOT_FOUND: 'COLUMN_NOT_FOUND', // Added for P2022
    INCONSISTENT_COLUMN_DATA: 'INCONSISTENT_COLUMN_DATA', // Added for P2023
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR', // Added for P1013, P1015

    // Database Record/Relationship Errors
    RELATED_RESOURCE_NOT_FOUND: 'RELATED_RESOURCE_NOT_FOUND', // Added for P2015
    RECORDS_NOT_CONNECTED: 'RECORDS_NOT_CONNECTED', // Added for P2017
    CONNECTED_RECORDS_NOT_FOUND: 'CONNECTED_RECORDS_NOT_FOUND', // Added for P2018

    // Database Feature/Support Errors
    UNSUPPORTED_FEATURE: 'UNSUPPORTED_FEATURE', // Added for P2026
    FULLTEXT_INDEX_NOT_FOUND: 'FULLTEXT_INDEX_NOT_FOUND', // Added for P2030

    // Database Transaction Errors
    TRANSACTION_ERROR: 'TRANSACTION_ERROR', // Added for P2028
    TRANSACTION_WRITE_CONFLICT: 'TRANSACTION_WRITE_CONFLICT', // Added for P2034
    MULTIPLE_QUERY_ERRORS: 'MULTIPLE_QUERY_ERRORS', // Added for P2027

    // Database-Specific Errors
    MONGODB_REPLICA_SET_REQUIRED: 'MONGODB_REPLICA_SET_REQUIRED', // Added for P2031

    // Migration Errors
    DATABASE_CREATION_FAILED: 'DATABASE_CREATION_FAILED', // Added for P3000
    DESTRUCTIVE_MIGRATION_DETECTED: 'DESTRUCTIVE_MIGRATION_DETECTED', // Added for P3001
    MIGRATION_ROLLBACK: 'MIGRATION_ROLLBACK', // Added for P3002

    // Introspection Errors
    INTROSPECTION_ERROR: 'INTROSPECTION_ERROR', // Added for P4000
    EMPTY_DATABASE: 'EMPTY_DATABASE', // Added for P4001
    INCONSISTENT_SCHEMA: 'INCONSISTENT_SCHEMA', // Added for P4002
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
